# Generated by Django 5.1.5 on 2025-03-28 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local', models.CharField(max_length=70, verbose_name='Local')),
            ],
        ),
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criticidade', models.CharField(choices=[('NORMAL', 'Normal'), ('URGENTE', 'Urgente'), ('EMERGENCIAL', 'Emergencial')], default='NORMAL', max_length=20, verbose_name='Criticidade')),
                ('titulo', models.CharField(max_length=30, verbose_name='Título')),
                ('descricao', models.TextField(verbose_name='Descrição da Ocorrência')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM ANDAMENTO', 'Em Andamento'), ('ENCERRADA', 'Encerrada')], max_length=20)),
                ('data_abertura', models.DateTimeField(auto_now_add=True, verbose_name='Data de abertura')),
                ('data_encerramento', models.DateTimeField(blank=True, null=True, verbose_name='Data de Encerramento')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencia', to='plantao_coi.local')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencia', to='plantao_coi.unidade')),
            ],
            options={
                'verbose_name': 'Ocorrência',
                'verbose_name_plural': 'Ocorrências',
            },
        ),
    ]
