# Generated by Django 5.1.5 on 2025-05-06 13:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DataSolicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='LocalExterno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('localizacao', models.CharField(blank=True, help_text='Localização do local', max_length=200, verbose_name='Localização')),
                ('endereco', models.CharField(blank=True, help_text='Endereço completo', max_length=300, verbose_name='Endereço')),
            ],
        ),
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LocalInterno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locais_internos', to='plantao_coi.ativo')),
                ('planta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locais_internos', to='plantao_coi.planta')),
            ],
            options={
                'verbose_name': 'Local Interno',
                'verbose_name_plural': 'Locais Internos',
            },
        ),
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30, verbose_name='Título')),
                ('data_solicitacao', models.DateTimeField(blank=True, null=True, verbose_name='Data da Solicitação')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('criticidade', models.CharField(choices=[('NORMAL', 'Normal'), ('URGENTE', 'Urgente'), ('EMERGENCIAL', 'Emergencial')], default='NORMAL', max_length=20, verbose_name='Criticidade')),
                ('status', models.CharField(choices=[('EM_ABERTO', 'Em Aberto'), ('CONCLUIDA', 'Concluída')], default='EM_ABERTO', max_length=10, verbose_name='Status')),
                ('local_externo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencias_externas', to='plantao_coi.localexterno', verbose_name='Local Externo')),
                ('local_interno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencias_internas', to='plantao_coi.localinterno', verbose_name='Local Interno')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencias', to='plantao_coi.unidade')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='Texto')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comentarios', to=settings.AUTH_USER_MODEL, verbose_name='Plantonista')),
                ('ocorrencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='plantao_coi.ocorrencia')),
            ],
        ),
        migrations.CreateModel(
            name='Plantao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('turno', models.CharField(choices=[('DIURNO', 'Diurno'), ('NOTURNO', 'Noturno')], max_length=10)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plantão',
                'verbose_name_plural': 'Plantões',
            },
        ),
    ]
