# Generated by Django 5.1.5 on 2025-05-09 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantao_coi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentario',
            options={'get_latest_by': 'data_criacao', 'ordering': ('-data_criacao',), 'verbose_name': 'Comentário', 'verbose_name_plural': 'Comentários'},
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='ordem_de_servico',
            field=models.CharField(max_length=13, verbose_name='OS'),
        ),
    ]
