# Generated by Django 5.1.5 on 2025-05-07 16:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantao_coi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocorrencia',
            name='data_solicitacao',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Data da Solicitação'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='descricao',
            field=models.TextField(default=1111, verbose_name='Descrição'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='local_externo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencias_externas', to='plantao_coi.localexterno', verbose_name='Local Externo'),
        ),
    ]
