# Generated by Django 5.1.5 on 2025-04-02 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantao_coi', '0003_dataabertura_dataencerramento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocorrencia',
            name='local',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencia', to='plantao_coi.local'),
        ),
    ]
