# Generated by Django 5.1.5 on 2025-04-02 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantao_coi', '0004_alter_ocorrencia_local'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocorrencia',
            name='status',
            field=models.CharField(choices=[('EM_ABERTO', 'Em Aberto'), ('CONCLUIDA', 'Concluida')], default='EM_ABERTO', max_length=10, verbose_name='Status'),
        ),
    ]
