# Generated by Django 5.1.5 on 2025-05-05 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantao_coi', '0008_alter_ocorrencia_descricao'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalExterno',
            fields=[
                ('local_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='plantao_coi.local')),
                ('endereco', models.CharField(max_length=100)),
                ('localizacao', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Local Externo',
            },
            bases=('plantao_coi.local',),
        ),
        migrations.CreateModel(
            name='LocalInterno',
            fields=[
                ('local_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='plantao_coi.local')),
                ('planta', models.CharField(max_length=50)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Local Interno',
            },
            bases=('plantao_coi.local',),
        ),
        migrations.AlterModelOptions(
            name='local',
            options={'verbose_name': 'Local'},
        ),
        migrations.RemoveField(
            model_name='local',
            name='local',
        ),
        migrations.AddField(
            model_name='local',
            name='tipo',
            field=models.CharField(choices=[('interno', 'Interno'), ('externo', 'Externo')], default='interno', max_length=10),
        ),
    ]
